# Generated by Django 3.1.4 on 2021-02-14 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=150)),
                ('trailer', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('rated', models.CharField(choices=[('PG', 'Rated Pg'), ('18+', 'Rated 18'), ('16+', 'Rated 16'), ('21+', 'Rated 21'), ('13+', 'Rated 13')], default='PG', max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=250)),
                ('cast', models.TextField()),
                ('description', models.TextField()),
                ('release_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField(null=True)),
                ('date', models.DateField(null=True)),
                ('is_screened', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.movie')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.hall')),
            ],
        ),
    ]
