# Generated by Django 3.1.4 on 2021-02-14 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('ASSIGNED', 'Assigned'), ('EMPTY', 'Empty')], default='EMPTY', max_length=50)),
                ('time_assigned', models.DateTimeField(default=django.utils.timezone.now)),
                ('seat_number', models.IntegerField(blank=True, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.hall')),
                ('screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screenings.screening')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seat_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
