# Generated by Django 3.1.4 on 2021-02-14 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
    ]
