# Generated by Django 3.1.4 on 2021-02-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_remove_seat_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'BOOKED'), ('ASSIGNED', 'ASSIGNED'), ('EMPTY', 'EMPTY')], default='EMPTY', max_length=50),
        ),
    ]
